### PR TITLE
UML Revamp

### PR DESCRIPTION
**Pull request by nyankoclaws**

### CODE REVIEW

**Comment by nyankoclaws** [comment]
Didn't remove anything, but reordered a significant amount of things for ease of readability. Mainly extended the Person attributes.

**Review by donwong2308 — APPROVED** [review]
LGTM

**Review by PallonCX — APPROVED** [review]
LGTM

**Review by larainezo — APPROVED** [review]
LGTM

**Review by JustWeiHao — APPROVED** [review]
LGTM

**Pull request merged**
