### PR TITLE
Add no duplicate prefix check for birthday and dormtag

### LINKED ISSUE #111: addCommandParser bug
```
argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ROOMNUMBER,
                PREFIX_TELEGRAM);
```

should include dormTag and birthday

### PR DESCRIPTION
**Pull request by PallonCX**
Closes #111

### CODE REVIEW

**Review by JustWeiHao — APPROVED** [review]
LGTM. Probably can add multiple test cases.

**Review by larainezo — APPROVED** [review]
LGTM

**Review by donwong2308 — APPROVED** [review]
LGTM

**Review by nyankoclaws — APPROVED** [review]
LGTM

**Pull request merged**
